# Generated by Django 5.1.5 on 2025-02-26 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_transactions', '0002_alter_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=datetime.date(2025, 2, 27)),
        ),
    ]
