# Generated by Django 5.1.5 on 2025-02-23 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_reviews_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='destinations',
        ),
        migrations.DeleteModel(
            name='reviews',
        ),
    ]
