# Generated by Django 5.1.5 on 2025-03-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loan_interest_amount_loan_monthly_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='monthly_payment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='loan',
            name='progress',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=12),
        ),
        migrations.AlterField(
            model_name='loan',
            name='remaining_months',
            field=models.IntegerField(default=0),
        ),
    ]
